name: Continuous Integration Pipeline
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
        build-type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Ubuntu Dependencies
        if: ${{startsWith(matrix.os, 'ubuntu')}}
        run: sudo apt-get install libboost-all-dev

      - name: Install macOS Dependencies
        if: ${{startsWith(matrix.os, 'macos')}}
        run: brew install boost

      - name: Configure
        run: cmake -B build/${{ matrix.build-type }} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build 
        run: cmake --build build/${{ matrix.build-type }}
