name: Continuous Integration Pipeline
on: [push]
jobs:
  ubuntu-build:
    strategy:
    matrix:
      build-type: [Debug, Release]
      os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install OS Dependencies
        run: sudo apt-get install libboost-all-dev libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev

      - name: Configure
        run: cmake -B build/${{ matrix.build-type }} -G "Unix Makefiles" -DXENOIDE_GUI_GTK3=ON -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build 
        run: cmake --build build/${{ matrix.build-type }}
